"""empty message

Revision ID: 6512d83d8a01
Revises: c8fe672be096
Create Date: 2018-04-16 21:29:14.874394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6512d83d8a01'
down_revision = 'c8fe672be096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('reporter_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'report', 'user', ['reporter_id'], ['guid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'reporter_id')
    # ### end Alembic commands ###
