"""empty message

Revision ID: 77964aff8a4f
Revises: 7d754ec573ec
Create Date: 2018-04-22 19:21:25.251624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77964aff8a4f'
down_revision = '7d754ec573ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
