"""empty message

Revision ID: ff97934b3ea5
Revises: df0eafa955aa
Create Date: 2018-04-08 17:29:07.881938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff97934b3ea5'
down_revision = 'df0eafa955aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('issued', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'issued')
    # ### end Alembic commands ###
